schema = 3

[mod]
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.7.0"
    hash = "sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.2"
    hash = "sha256-ukxk1Cfm6cQW18g/aa19tLcUu5BnF7VmfAvrDHAOl6A="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.4.0"
    hash = "sha256-7I1Oatc7GAaHgAqBFO6Tv4IbzFiYeU9bJAfJhXuWaXk="
  [mod."github.com/sagikazarmark/slog-shim"]
    version = "v0.1.0"
    hash = "sha256-F92BQXXmn3mCwu3mBaGh+joTRItQDSDhsjU6SofkYdA="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.0"
    hash = "sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko="
  [mod."github.com/spf13/afero"]
    version = "v1.11.0"
    hash = "sha256-+rV3cDZr13N8E0rJ7iHmwsKYKH+EhV+IXBut+JbBiIE="
  [mod."github.com/spf13/cast"]
    version = "v1.6.0"
    hash = "sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.19.0"
    hash = "sha256-MZ8EAvdgpGbw6kmUz8UOaAAAMdPPGd14TrCBAY+A1T4="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240506185415-9bf2ced13842"
    hash = "sha256-5JZE4OhePWHtObIT4RJOS+2zv265Io1yJkFeE8wHXY4="
  [mod."golang.org/x/sys"]
    version = "v0.20.0"
    hash = "sha256-mowlaoG2k4n1c1rApWef5EMiXd3I77CsUi8jPh6pTYA="
  [mod."golang.org/x/text"]
    version = "v0.15.0"
    hash = "sha256-pBnj0AEkfkvZf+3bN7h6epCD2kurw59clDP7yWvxKlk="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
